[package]
name = "mlua_bindgen"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua = {version="0.10.1", features=["luau"]}
macros = {path="./macros"}

[dev-dependencies]
mlua = {version="0.10.1", features=["luau", "macros"]}